


apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels: # these are replicaset labels
    app: mysql
    tier: db
    project: expense
spec:
  # modify replicas according to your case
  replicas: 1
  selector:
    # these are used to select the pod to create replicas
    matchLabels:
      app: mysql
      tier: db
      project: expense
  # this is pod definition
  template:
    metadata:
      # these labels belongs to pod
      labels:
        app: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: rajesh2219/mysql:v1
        readinessProbe:
          tcpSocket:
            port: 3306
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
         tcpSocket:
           port: 3306
         initialDelaySeconds: 15
         periodSeconds: 10
       
---
kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    app: mysql
    tier: db
    project: expense
  ports:
  - name: mysql-svc-port
    protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port
